- name: update-debian
  hosts: debian
  become: true
  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Upgrade
      apt:
        upgrade: dist

    - name: Remove unused
      apt:
        autoremove: yes
        purge: yes
