- name: update-opnsense
  hosts: opnsense
  become: true
  vars:
    firewall_key: "{{ lookup('env', 'firewall_key') }}"
    firewall_secret: "{{ lookup('env', 'firewall_secret') }}"
  tasks:
  
  - name: Update
    oxlorg.opnsense.system:
      action: 'update'
      firewall: "{{ ansible_host }}"
      api_key: "{{ firewall_key }}"
      api_secret: "{{ firewall_secret }}"
  - name: Upgrade
    oxlorg.opnsense.system:
      action: 'upgrade'
      firewall: "{{ ansible_host }}"
      api_key: "{{ firewall_key }}"
      api_secret: "{{ firewall_secret }}"