- name: update-opnsense
  hosts: opnsense
  become: true
  tasks:
  - name: Update
    oxlorg.opnsense.system:
      action: 'update'
      firewall: "{{ ansible_host }}"
  - name: Upgrade
    oxlorg.opnsense.system:
      action: 'upgrade'
      firewall: "{{ ansible_host }}"