- name: update-opnsense
  hosts: opnsense
  become: true
  tasks:
  - name: Update
    oxlorg.opnsense.system:
      action: 'update'
      
  - name: Upgrade
    oxlorg.opnsense.system:
      action: 'upgrade'